apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web
  namespace: bakseter-net
spec:
  entryPoints:
    - public
  routes:
    - kind: Rule
      match: Host(`bakseter.net`)
      services:
        - name: web
          port: 80
